name: Veille DevOps Hebdomadaire (Lundi 9h)

on:
  schedule:
    # 07:00 UTC = 09:00 France (Heure d'été)
    # Le '1' à la fin signifie Lundi (Monday)
    - cron: '0 7 * * 1'
  workflow_dispatch:   # Indispensable pour ton premier lancement manuel

jobs:
  run_bot:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.10'
      - name: Install dependencies
        run: pip install requests pandas
      - name: Executer l'agent
        env:
          RAPID_API_KEY: ${{ secrets.RAPID_API_KEY }}
          DISCORD_WEBHOOK: ${{ secrets.DISCORD_WEBHOOK }}
        run: python main.py
