name: Veille DevOps Quotidienne (12h - 18h)

on:
  schedule:
    # 10:00 UTC = 12:00 France | 16:00 UTC = 18:00 France
    - cron: '0 10,16 * * *'
  workflow_dispatch: # Pour tester manuellement

jobs:
  run_bot:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v4
        with:
          python-version: '3.9'
      - run: pip install requests
      - name: Exécution de l'agent
        env:
          RAPID_API_KEY: ${{ secrets.RAPID_API_KEY }}
          SLACK_URL: ${{ secrets.DISCORD_WEBHOOK }}
        run: python main.py
